servers: '10.0.1.256,10.0.2.256'
installs:
  swapspace: yes
  nginx: yes
  php:
    install: yes
    composer: yes
    version: 8.3
  node_and_npm: yes
  redis: yes
  sqlite: yes
  database:
    mysql: yes
    mariadb: no
    root_password: secret
  certbot: yes
  apache: no
  memcache: no
  beanstalk: no
  mailhog: no
  ngrok: no
  postfix: no



